### ISSUE TITLE
グラフ機能の実装が上手くいかない

### ISSUE THREAD

**Issue by inagakiyuya** [inagakiyuya/stressdiary#3]
グラフ機能を実装しようとしているのですが、上手くいかないです。

前提
Railsは7系を使用しています。オプションはesbuildです。
ユーザーは日記を投稿することができます。日記の投稿後、ストレス診断と幸福度診断を行い、診断結果によりストレス値と幸福度が0点~100点で算出されます。
グラフ機能を実装するためにgem "chart kick"を使用しています。

やりたいこと
算出されたストレス値と幸福度をgem "chart kick"を用いることでグラフ化したいです。

今起きている問題やエラー
ターミナル上のログやsafariのデベロッパーツール上では、グラフ機能を実装するために必要な値が取得できていることが確認できているが、グラフが表示されずにずっとLoadingという表示された状態で、期待通りの挙動が確認できない。

自分のコード
gem file
```
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.1"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.5"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Bundle and transpile JavaScript [https://github.com/rails/jsbundling-rails]
gem "jsbundling-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Bundle and process CSS [https://github.com/rails/cssbundling-rails]
gem "cssbundling-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
gem "image_processing", "~> 1.2"
gem "sorcery"
gem "ransack"
gem "bootstrap"
gem "font-awesome-sass"
gem "jquery-rails"
gem "faker"
gem "draper"
gem "mini_magick"
gem "kaminari"
gem "chartkick"
gem "byebug"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
```

app/controllers/mypage/profiles_controller.rb
```
class Mypage::ProfilesController < Mypage::BaseController
  def show
    @user = current_user
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(profile_params)
      redirect_to mypage_profile_path, success: 'プロフィールを更新しました'
    else
      render :show
    end
  end

  def view_users
    @user = User.find(params[:id])
  end

  def mymean
    @means = current_user.means.includes(:user).order(created_at: :desc).page(params[:page]).per(10)
  end

  def bookmarks
    bookmarks = Bookmark.where(user_id: current_user.id).pluck(:mean_id)
    @bookmark_means = Mean.find(bookmarks)
  end

  def mydiary
    @diaries = current_user.diaries.includes(:user, :stress_diagnosis, :happy_diagnosis).order(created_at: :desc).page(params[:page]).per(10)
  end

  def favorites
    favorites = Favorite.where(user_id: current_user.id).pluck(:diary_id)
    @favorite_diaries = Diary.find(favorites)
  end

  def stress_chart
    @diaries = current_user.diaries.includes(:stress_diagnosis)
    @stress_datas = @diaries
                    .joins(:stress_diagnosis)
                    .where('diaries.created_at >= ?', 31.days.ago)
                    .where('stress_diagnoses.stress_count >= ?', 0)
                    .select("date(diaries.created_at) as date, stress_diagnoses.stress_count")
                    .order("date ASC")
                    .group_by { |d| d.date }

    @stress_datas.each do |date, rows|
      sum_stress_count = rows.map(&:stress_count).sum
      puts "#{date} のストレス値: #{sum_stress_count}"
    end
  end

  def happy_chart
    @diaries = current_user.diaries.includes(:happy_diagnosis)
    @happy_datas = @diaries
                   .joins(:happy_diagnosis)
                   .where('diaries.created_at >= ?', 31.days.ago)
                   .where('happy_diagnoses.happy_count >= ?', 0)
                   .select("date(diaries.created_at) as date, happy_diagnoses.happy_count")
                   .order("date ASC")
                   .group_by { |d| d.date }

    @happy_datas.each do |date, rows|
      sum_happy_count = rows.map(&:happy_count).sum
      puts "#{date} の幸福値: #{sum_happy_count}"
    end
  end

  def like_ranking
    User.all.each(&:update_total_like_counts)
    @user_like_ranks = User.all.order(total_like_counts: :desc).limit(10)
  end

  def like_ranking_in_past_month
    User.all.each(&:update_total_like_counts_in_past_month)
    @user_like_ranks_in_past_month = User.all.order(total_like_counts_in_past_month: :desc).limit(10)
  end

  def like_ranking_in_past_week
    User.all.each(&:update_total_like_counts_in_past_week)
    @user_like_ranks_in_past_week = User.all.order(total_like_counts_in_past_week: :desc).limit(10)
  end

  def sympathy_ranking
    User.all.each(&:update_total_sympathy_counts)
    @user_sympathy_ranks = User.all.order(total_sympathy_counts: :desc).limit(10)
  end

  def sympathy_ranking_in_past_month
    User.all.each(&:update_total_sympathy_counts_in_past_month)
    @user_sympathy_ranks_in_past_month = User.all.order(total_sympathy_counts_in_past_month: :desc).limit(10)
  end

  def sympathy_ranking_in_past_week
    User.all.each(&:update_total_sympathy_counts_in_past_week)
    @user_sympathy_ranks_in_past_week = User.all.order(total_sympathy_counts_in_past_week: :desc).limit(10)
  end

  private

  def profile_params
    params.require(:user).permit(:name, :email, :password, :avatar, 
                                 :total_sympathy_counts, :total_sympathy_counts_in_past_month, :total_sympathy_counts_in_past_week,
                                 :total_like_counts, :total_like_counts_in_past_month, :total_like_counts_in_past_week)
  end
end
```

app/javascript/application.js
```
// Entry point for the build script in your package.json
import "@hotwired/turbo-rails"
import "./controllers"
import * as bootstrap from "bootstrap"

import $ from 'jquery'
import { Tooltip } from "bootstrap"

$('[data-bs-toggle="tooltip"]').each((idx, elm) => {
  new Tooltip(elm)
})

import "chartkick/chart.js"
```

app/views/mypage/profiles/stress_chart.html.erb
```
<div>
  <h2>ストレス値変化の推移</h2>
  <div class="chart">
    <%= line_chart @stress_datas %>
  </div>
</div>
```
app/views/mypage/profiles/happy_chart.html.erb
```
<div>
  <h2>幸福度変化の推移</h2>
  <div class="chart">
    <%= line_chart @happy_datas %>
  </div>
</div>
```

以下がターミナル上のログになります。
```
Started GET "/mypage/profile/stress_chart" for ::1 at 2023-07-13 16:58:45 +0900
Processing by Mypage::ProfilesController#stress_chart as HTML
  User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:18:in `current_user'
  SQL (1.5ms)  SELECT date(diaries.created_at) as date, stress_diagnoses.stress_count, "diaries"."id" AS t0_r0, "stress_diagnoses"."id" AS t1_r0, "stress_diagnoses"."stress_count" AS t1_r1, "stress_diagnoses"."diary_id" AS t1_r2, "stress_diagnoses"."answer1" AS t1_r3, "stress_diagnoses"."answer2" AS t1_r4, "stress_diagnoses"."answer3" AS t1_r5, "stress_diagnoses"."answer4" AS t1_r6, "stress_diagnoses"."answer5" AS t1_r7, "stress_diagnoses"."answer6" AS t1_r8, "stress_diagnoses"."answer7" AS t1_r9, "stress_diagnoses"."answer8" AS t1_r10, "stress_diagnoses"."answer9" AS t1_r11, "stress_diagnoses"."answer10" AS t1_r12, "stress_diagnoses"."answer11" AS t1_r13, "stress_diagnoses"."answer12" AS t1_r14, "stress_diagnoses"."answer13" AS t1_r15, "stress_diagnoses"."answer14" AS t1_r16, "stress_diagnoses"."answer15" AS t1_r17, "stress_diagnoses"."answer16" AS t1_r18, "stress_diagnoses"."answer17" AS t1_r19, "stress_diagnoses"."answer18" AS t1_r20, "stress_diagnoses"."answer19" AS t1_r21, "stress_diagnoses"."answer20" AS t1_r22, "stress_diagnoses"."answer21" AS t1_r23, "stress_diagnoses"."answer22" AS t1_r24, "stress_diagnoses"."answer23" AS t1_r25, "stress_diagnoses"."answer24" AS t1_r26, "stress_diagnoses"."answer25" AS t1_r27, "stress_diagnoses"."created_at" AS t1_r28, "stress_diagnoses"."updated_at" AS t1_r29 FROM "diaries" INNER JOIN "stress_diagnoses" ON "stress_diagnoses"."diary_id" = "diaries"."id" WHERE "diaries"."user_id" = $1 AND (diaries.created_at >= '2023-06-12 07:58:45.090056') AND (stress_diagnoses.stress_count >= 0) ORDER BY date ASC  [["user_id", 1]]
  ↳ app/controllers/mypage/profiles_controller.rb:45:in `group_by'
2023-06-17 のストレス値: 16
2023-06-26 のストレス値: 8
2023-07-02 のストレス値: 8
2023-07-13 のストレス値: 8
  Rendering layout mypage/layouts/application.html.erb
  Rendering mypage/profiles/stress_chart.html.erb within mypage/layouts/application
  Rendered mypage/profiles/stress_chart.html.erb within mypage/layouts/application (Duration: 0.2ms | Allocations: 339)
  Rendered shared/_header.html.erb (Duration: 0.1ms | Allocations: 283)
  Rendered mypage/shared/_sidebar.html.erb (Duration: 0.2ms | Allocations: 395)
  Rendered shared/_footer.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered layout mypage/layouts/application.html.erb (Duration: 2.2ms | Allocations: 3020)
Completed 200 OK in 9ms (Views: 2.4ms | ActiveRecord: 2.0ms | Allocations: 5722)
```

```
Started GET "/mypage/profile/happy_chart" for ::1 at 2023-07-13 17:01:38 +0900
Processing by Mypage::ProfilesController#happy_chart as HTML
  User Load (1.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:18:in `current_user'
  SQL (13.2ms)  SELECT date(diaries.created_at) as date, happy_diagnoses.happy_count, "diaries"."id" AS t0_r0, "happy_diagnoses"."id" AS t1_r0, "happy_diagnoses"."happy_count" AS t1_r1, "happy_diagnoses"."diary_id" AS t1_r2, "happy_diagnoses"."question1" AS t1_r3, "happy_diagnoses"."question2" AS t1_r4, "happy_diagnoses"."question3" AS t1_r5, "happy_diagnoses"."question4" AS t1_r6, "happy_diagnoses"."question5" AS t1_r7, "happy_diagnoses"."question6" AS t1_r8, "happy_diagnoses"."question7" AS t1_r9, "happy_diagnoses"."question8" AS t1_r10, "happy_diagnoses"."question9" AS t1_r11, "happy_diagnoses"."question10" AS t1_r12, "happy_diagnoses"."created_at" AS t1_r13, "happy_diagnoses"."updated_at" AS t1_r14 FROM "diaries" INNER JOIN "happy_diagnoses" ON "happy_diagnoses"."diary_id" = "diaries"."id" WHERE "diaries"."user_id" = $1 AND (diaries.created_at >= '2023-06-12 08:01:38.070859') AND (happy_diagnoses.happy_count >= 0) ORDER BY date ASC  [["user_id", 1]]
  ↳ app/controllers/mypage/profiles_controller.rb:62:in `group_by'
2023-06-17 の幸福値: 40
2023-06-26 の幸福値: 60
2023-07-02 の幸福値: 70
2023-07-13 の幸福値: 70
  Rendering layout mypage/layouts/application.html.erb
  Rendering mypage/profiles/happy_chart.html.erb within mypage/layouts/application
  Rendered mypage/profiles/happy_chart.html.erb within mypage/layouts/application (Duration: 3.7ms | Allocations: 466)
  Rendered shared/_header.html.erb (Duration: 0.5ms | Allocations: 283)
  Rendered mypage/shared/_sidebar.html.erb (Duration: 0.4ms | Allocations: 395)
  Rendered shared/_footer.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered layout mypage/layouts/application.html.erb (Duration: 10.2ms | Allocations: 3147)
Completed 200 OK in 38ms (Views: 10.9ms | ActiveRecord: 14.2ms | Allocations: 5798)
```

以下がsafariのデベロッパーツールの表示になります。
```
            <div class="col-lg-9 col-md-8 col-12">
              <div>
  <h2>ストレス値変化の推移</h2>
  <div class="chart">
    <div id="chart-1" style="height: 300px; width: 100%; text-align: center; color: #999; line-height: 300px; font-size: 14px; font-family: 'Lucida Grande', 'Lucida Sans Unicode', Verdana, Arial, Helvetica, sans-serif;">Loading...</div>
<script>
  (function() {
    if (document.documentElement.hasAttribute("data-turbolinks-preview")) return;
    if (document.documentElement.hasAttribute("data-turbo-preview")) return;

    var createChart = function() { new Chartkick["LineChart"]("chart-1", [["2023-06-17",[{"id":1,"date":"2023-06-17","stress_count":16}]],["2023-06-26",[{"id":2,"date":"2023-06-26","stress_count":8}]],["2023-07-02",[{"id":3,"date":"2023-07-02","stress_count":8}]],["2023-07-13",[{"id":4,"date":"2023-07-13","stress_count":8}]]], {}); };
    if ("Chartkick" in window) {
      createChart();
    } else {
      window.addEventListener("chartkick:load", createChart, true);
    }
  })();
</script>

  </div>
</div>
```

```
            <div class="col-lg-9 col-md-8 col-12">
              <div>
  <h2>幸福度変化の推移</h2>
  <div class="chart">
    <div id="chart-1" style="height: 300px; width: 100%; text-align: center; color: #999; line-height: 300px; font-size: 14px; font-family: 'Lucida Grande', 'Lucida Sans Unicode', Verdana, Arial, Helvetica, sans-serif;">Loading...</div>
<script>
  (function() {
    if (document.documentElement.hasAttribute("data-turbolinks-preview")) return;
    if (document.documentElement.hasAttribute("data-turbo-preview")) return;

    var createChart = function() { new Chartkick["LineChart"]("chart-1", [["2023-06-17",[{"id":1,"date":"2023-06-17","happy_count":40}]],["2023-06-26",[{"id":2,"date":"2023-06-26","happy_count":60}]],["2023-07-02",[{"id":3,"date":"2023-07-02","happy_count":70}]],["2023-07-13",[{"id":4,"date":"2023-07-13","happy_count":70}]]], {}); };
    if ("Chartkick" in window) {
      createChart();
    } else {
      window.addEventListener("chartkick:load", createChart, true);
    }
  })();
</script>

  </div>
</div>
```
行ったこと
参考文献
https://horicontent.com/program/rubyonrails/graph/
https://chartkick.com/#esbuild-rollup-js-or-webpack

上記のサイトの指示の通りに　まず、yarn add chartkick chart.jsを行い、
次にapp/javascript/application.jsにimport "chartkick/chart.js"の記述を追加したのですが、上手くいきませんでした。

**Comment by Tsuchiya2** [comment]
[こちらの記事](https://horicontent.com/program/rubyonrails/graph/)はRailsが７系かどうか、esbuildを使用するものなのかどうかが書かれていないので、現状のアプリと同じ状況とは判断が難しいので参考までに留めておきましょう。

もう１つの公式の方を参考に取り組んでみましょう。
[公式のこの記載部分](https://chartkick.com/#esbuild-rollup-js-or-webpack:~:text=%22Chart.bundle%22-,esbuild%2C%20rollup.js%2C%20or%20Webpack,-Run%3A)は既に対応済みでしょうか。念のためyarn部分も行ってみてください。

あと[公式のこの記載](https://chartkick.com/#esbuild-rollup-js-or-webpack:~:text=%3C%25%3D%20line_chart%20User.group_by_day(%3Acreated_at).count%20%25%3E)から察するにオブジェクトではなくinteger型？を渡す必要性もありそうなので、何を渡しているか等々確認してみてください。

**Comment by inagakiyuya** [comment]
お疲れ様です。
公式で紹介されている方法は既に実行済みです。
念のために再度yarnの部分を行った際のログが以下の通りになりました。
```
inagakiyuya@inagakiyuuyanoMacBook-Pro stressdiary % yarn add chartkick chart.js
yarn add v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning Pattern ["chart.js@^4.3.0"] is trying to unpack in the same destination "/Users/inagakiyuya/Library/Caches/Yarn/v6/npm-chart-js-4.3.0-ac363030ab3fec572850d2d872956f32a46326a1-integrity/node_modules/chart.js" as pattern ["chart.js@4"]. This could result in non-deterministic behavior, skipping.
warning chart.js@4.3.0: The engine "pnpm" appears to be invalid.
warning chart.js@4.3.0: The engine "pnpm" appears to be invalid.
[3/4] 🔗  Linking dependencies...
warning "admin-lte > bootstrap-switch@3.3.4" has incorrect peer dependency "bootstrap@^3.1.1".
warning "admin-lte > tempusdominus-bootstrap-4@5.39.2" has unmet peer dependency "moment-timezone@^0.5.31".
warning "admin-lte > tempusdominus-bootstrap-4@5.39.2" has unmet peer dependency "tempusdominus-core@5.19.3".
warning " > bootstrap@4.5.3" has unmet peer dependency "popper.js@^1.16.1".
[4/4] 🔨  Building fresh packages...
success Saved 2 new dependencies.
info Direct dependencies
├─ chart.js@4.3.0
└─ chartkick@5.0.1
info All dependencies
├─ chart.js@4.3.0
└─ chartkick@5.0.1
✨  Done in 1.56s.
```

また、app/javascript/application.jsのファイルの内容は以下のようになります。
app/javascript/application.js
```
// Entry point for the build script in your package.json
import "@hotwired/turbo-rails"
import "./controllers"
import * as bootstrap from "bootstrap"

import $ from 'jquery'
import { Tooltip } from "bootstrap"

$('[data-bs-toggle="tooltip"]').each((idx, elm) => {
  new Tooltip(elm)
})

import "chartkick/chart.js"
```
公式で紹介されている方法を行っても上手くいきませんでした。

次にデータ型を確認しました。
おっしゃる通り、chartkickの公式サイトではデータ型がhashかarrayかURLと書いてありました。なので、渡すデータ型に気をつけてコードを編集しました。
幸福度、ストレス値それぞれに対してグラフ機能を実装しなければならないので、実験として幸福度の方は配列型に修正、ストレス値の方はハッシュ型に修正しました。そして、上手くいった方のデータ型でグラフ機能を実装することを考えました。
以下が自分の編集後のコードです。
幸福度
app/views/mypage/profiles/happy_chart.html.erb
```
<div>
  <h2>幸福度変化の推移</h2>
  <div class="chart">
    <%= line_chart @happy_datas %>
  </div>
</div>
```

app/controllers/mypage/profiles_controller.rb
```
def happy_chart
    @diaries = current_user.diaries.includes(:happy_diagnosis)
    @happy_datas = @diaries
                   .joins(:happy_diagnosis)
                   .where('diaries.created_at >= ?', 31.days.ago)
                   .where('happy_diagnoses.happy_count >= ?', 0)
                   .select("date(diaries.created_at) as date, happy_diagnoses.happy_count")
                   .order("date ASC")
                   .group_by { |d| d.date }
                   .map { |date, rows| [date.to_s, rows.sum(&:happy_count)] }
  end
```

ターミナル上でのログになります
```
(byebug) @happy_datas
[["2023-06-17", 40], ["2023-06-26", 60], ["2023-07-02", 70], ["2023-07-13", 70]]
```

以下が編集後のコードです。
ストレス値
app/controllers/mypage/profiles_controller.rb
```
def stress_chart
    @diaries = current_user.diaries.includes(:stress_diagnosis)
    @stress_datas = @diaries
                    .joins(:stress_diagnosis)
                    .where('diaries.created_at >= ?', 31.days.ago)
                    .where('stress_diagnoses.stress_count >= ?', 0)
                    .select("date(diaries.created_at) as date, stress_diagnoses.stress_count")
                    .order("date ASC")
                    .group_by { |d| d.date }
                    .map { |date, rows| [date.to_s, rows.sum(&:stress_count)] }
                    .to_h
  end
```

app/views/mypage/profiles/stress_chart.html.erb
```
<div>
  <h2>ストレス値変化の推移</h2>
  <div class="chart">
    <%= line_chart @stress_datas %>
  </div>
</div>
```

以下がターミナル上のログです。
```
@stress_datas
{"2023-06-17"=>16, "2023-06-26"=>8, "2023-07-02"=>8, "2023-07-13"=>8}
```

データ型をそれぞれ、配列型、ハッシュ型の2通りに修正して、それぞれの場合で確認をしてみたのですが、どちらの場合でもLoadingの状態から変化することはありませんでした。

**Comment by kenchasonakai** [comment]
Rails7系でChartkickの動作確認を行ったのですが普通に公式通りにやって動きましたね
https://github.com/kenchasonakai/rails7_sample/pull/1
↑参考にしてみてください

`<%= line_chart @stress_datas %>`で変数を渡すのではなく

```
<%= line_chart {"2023-06-17"=>16, "2023-06-26"=>8, "2023-07-02"=>8, "2023-07-13"=>8} %>
```
のように値をベタ書きしてグラフが描画されるか確認したり、
そもそもJavaScriptが読み込まれているか確認したり(console.logなどを使うのが一般的ですね)、
検証ツールにエラーが出ていないか確認するなどしてどこに原因があるのか探ってみてください

**Comment by inagakiyuya** [comment]
グラフが正常に描写されない理由がわかりました。
2点あります。
1. yarn build　コマンドを実行していなかったため、app/javascript/application.jsの内容がPFに読み込まれていなかったことです。
2. app/views/mypage/layouts/application.html.erbに
<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>の記載がなかったため、app/views/mypage以下のビューにjsが読み込まれていなかったことです。
