### ISSUE TITLE
ストレス解消法のタグが上手く保存できない

### ISSUE THREAD

**Issue by inagakiyuya** [inagakiyuya/stressdiary#6]
前提：Rails7系でesbuildを用いています。
目的：レコメンド機能を実装するにあたって、ストレス解消法のmeansテーブルにcategoryのカラムを追加し、フォーム画面でクリックしたチェックボックスの値が保存できるようにしたい

ここの部分が上手くいけば、usersテーブルに、hobbyカラムを追加し、選択したhobbyの値とcategoryが一致するようなストレス解消法をランダムにユーザーに提示することでレコメンド機能を実装していこうと思います。

起きている問題：chatgptや参考文献を参考に、mean_paramsメソッドにcategoryカラムを追加した。parameterで値がとれてきているにも関わらず、エラーが生じ、保存できない。

以下がターミナルのログです。
```
Started POST "/means" for ::1 at 2023-08-14 02:46:44 +0900
02:46:44 web.1  | Processing by MeansController#create as TURBO_STREAM
02:46:44 web.1  |   Parameters: {"authenticity_token"=>"[FILTERED]", "mean"=>{"title"=>"test2", "situation"=>"test2", "approach"=>"test2", "result"=>"test2", "categories"=>"読書・漫画"}, "commit"=>"ストレス解消法を作成"}
02:46:44 web.1  |   User Pluck (0.6ms)  SELECT "users"."name", "users"."id" FROM "users"
02:46:44 web.1  |   ↳ app/controllers/application_controller.rb:19:in `suggest_user_name'
02:46:44 web.1  |   User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 12], ["LIMIT", 1]]
02:46:44 web.1  |   ↳ app/controllers/application_controller.rb:31:in `current_user'
02:46:44 web.1  | Unpermitted parameter: :categories. Context: { controller: MeansController, action: create, request: #<ActionDispatch::Request:0x0000000106675140>, params: {"authenticity_token"=>"[FILTERED]", "mean"=>{"title"=>"test2", "situation"=>"test2", "approach"=>"test2", "result"=>"test2", "categories"=>"読書・漫画"}, "commit"=>"ストレス解消法を作成", "controller"=>"means", "action"=>"create"} }

```

以下が自分のコードです。
app/controllers/mean_controller.rb
```
def mean_params
    params.require(:mean).permit(:title, :situation, :approach, :result, categories: {})
  end
```

app/views/means/_form.html.erb
```
<div class="mean-form">
  <%= form_with model: mean, local: true do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label :"タイトル" %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :"ストレスを感じた状況" %>
      <%= f.text_area :situation, class: 'form-control', rows: 3 %>
    </div>
    <div class="form-group">
      <%= f.label :"ストレスを取り除くために行なったこと" %>
      <%= f.text_area :approach, class: 'form-control', rows: 3 %>
    </div>
    <div class="form-group">
      <%= f.label :"行動をした結果" %>
      <%= f.text_area :result, class: 'form-control', rows: 3 %>
    </div>
    <p>カテゴリータグ</p>
    <ul class="cs-cboxtags">
      <div class="field">
        <li>
          <%= f.check_box :categories, { checked: false }, "グルメ", false %>
          <%= f.label :categories, "グルメ" %>
        </li>
        <li>
          <%= f.check_box :categories, { checked: false }, "スポーツ", false %>
          <%= f.label :categories, "スポーツ" %>
        </li>
        <li>
          <%= f.check_box :categories, { checked: false }, "旅行・お出かけ", false %>
          <%= f.label :categories, "旅行・お出かけ" %>
        </li>
        <li>
          <%= f.check_box :categories, { checked: false }, "読書・漫画", false %>
          <%= f.label :categories, "読書・漫画" %>
        </li>
        <li>
          <%= f.check_box :categories, { checked: false }, "映画・動画", false %>
          <%= f.label :categories, "映画・動画" %>
        </li>
      </div>
      <div class="field">
        <li>
          <%= f.check_box :categories, { checked: false }, "音楽", false %>
          <%= f.label :categories, "音楽" %>
        </li>
        <li>
          <%= f.check_box :categories, { checked: false }, "ゲーム", false %>
          <%= f.label :categories, "ゲーム" %>
        </li>
        <li>
          <%= f.check_box :categories, { checked: false }, "その他・屋内", false %>
          <%= f.label :categories, "その他・屋内" %>
        </li>
        <li>
          <%= f.check_box :categories, { checked: false }, "その他・屋外", false %>
          <%= f.label :categories, "その他・屋外" %>
        </li>
      </div>
    </ul>
  
    <%= f.submit 'ストレス解消法を作成', class: 'btn btn-primary' %>
  <% end %>
</div>
```

以下がマイグレーションファイルです。
db/migrate/20230813104137_add_category_to_means.rb
```
class AddCategoryToMeans < ActiveRecord::Migration[7.0]
  def change
    add_column :means, :categories, :string, array: true, default: '{}'
  end
end
```

マイグレーションの実行も確認しました。
```
inagakiyuya@inagakiyuuyanoMacBook-Pro stressdiary % rails db:migrate:status

database: stressdiary_development

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20230601072416  Sorcery core
   up     20230601074434  Create means
   up     20230604013217  Create mean comments
   up     20230604170234  Create bookmarks
   up     20230606154604  Create active storage tablesactive storage
   up     20230607053403  Create likes
   up     20230607185600  Create diaries
   up     20230609180805  Create stress diagnoses
   up     20230609181248  Create happy diagnoses
   up     20230613080342  Add role to users
   up     20230615084303  Create favorites
   up     20230615084409  Create diary comments
   up     20230615084607  Create sympathies
   up     20230619071251  Add counts to users
   up     20230629125807  Add four count columns to users
   up     20230630092443  Create reports
   up     20230803082745  Create reminders
   up     20230813104137  Add category to means
```

参考文献
https://pikawaka.com/rails/strong_parameter
https://zykbgame.hateblo.jp/entry/2021/12/24/030742
https://qiita.com/mattan5271/items/79bd889b57e207d5a2c9

**Comment by kenchasonakai** [comment]
エラーの丸投げになってしまっているように感じますので、
まず、どんなエラーが起きているのか、そもそもどんなparamsが送られてきているのかをどのような形式であればDBにcategoriesのデータが保存できるのかを確認してどのような対処をするべきなのかをご自身で調べて試行錯誤してみてください

また、categoryを複数持つのであれば中間テーブルを作成するような形でも実現できるかと思いますので他に実装方法がないかも合わせて調べてみて下さい

**Comment by inagakiyuya** [comment]
お疲れ様です。
DBに保存されるデータ型に気を遣った結果、カテゴリー機能は実装できました。
アドバイスの方、ありがとうございます。
中間試験の方でも、タグ機能を扱っており、その際は中間テーブルを作成していましたが、その分手間がかかるので、中間テーブルを作成しない方法で今回は実装しました。
参考文献
https://qiita.com/kawakami_shotaro/items/11a677bf34136cb7686d
